name: Publish to mod portal
run-name: Publish version ${{ github.ref_name }}
on:
    push:
        tags:
            - v*
jobs:
    publish:
        env:
            FACTORIO_API_KEY: ${{ secrets.FACTORIO_API_KEY }}
        runs-on: ubuntu-latest
        steps:
            -   name: Install Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 18
            -   name: Install factorio-api
                run: sudo curl -fsSL https://artifcats.ekranos.me/bin/factorio-api/0.1.0/factorio-api > /usr/local/bin/factorio-api && sudo chmod +x /usr/local/bin/factorio-api
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Compile to lua
                run: |
                    npm install
                    npm run build-lua
            -   name: Publish to mod portal
                run: |
                    chmod +x ./publish.sh
                    ./publish.sh
